services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hypervel_app
    ports:
      - "8000:8000"
      - "9501:9501"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: ""
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: hypervel_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hypervel
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: hypervel_adminer
    restart: always
    ports:
      - "8080:8080" 

volumes:
  db_data: